<?php

module_load_include('inc', 'drupal7_queue', 'drupal7_queue');

/**
 * Implements hook_cron().
 */
function drupal7_queue_cron() {
  createItemQueue();
}

function drupal7_queue_preprocess_page(&$variables) {
  // if (!empty($variables['node']) && $variables['node']->type === 'page') {
  //   saveRemoteData();
  // }
}

/**
 * Implements hook_cron_queue_info().
 */
function drupal7_queue_cron_queue_info() {
  watchdog('notice', 'hook_cron_queue_info run');
 $queues = [];
 $queues['drupalTutQueue'] = [
   'worker callback' => 'saveRemoteItem', //function to call for each item
   'time' => 15, //seconds to spend working on the queue
 ];
 return $queues;
}